[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM46
lib_deps =
    bblanchon/ArduinoJson@^6.21.4
    knolleary/PubSubClient@^2.8 
    tikaflow/UTF8ToGB2312 @ ^1.1.52
